# Generated by Django 4.2.7 on 2025-06-01 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='이메일')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호 해시')),
                ('channel_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='채널 1')),
                ('channel_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='채널 2')),
                ('channel_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='채널 3')),
                ('channel_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='채널 4')),
                ('channel_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='채널 5')),
                ('send_time', models.TimeField(default='08:00:00', verbose_name='메일 발송 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '구독 정보',
                'verbose_name_plural': '구독 정보들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('pending', '대기중')], default='pending', max_length=20, verbose_name='발송 상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('video_count', models.IntegerField(default=0, verbose_name='처리된 영상 수')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='subscriptions.subscription', verbose_name='구독 정보')),
            ],
            options={
                'verbose_name': '이메일 로그',
                'verbose_name_plural': '이메일 로그들',
                'ordering': ['-sent_at'],
            },
        ),
    ]
