# Generated by Django 4.2.7 on 2025-06-01 04:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': '이메일 로그', 'verbose_name_plural': '이메일 로그 목록'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': '구독', 'verbose_name_plural': '구독 목록'},
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='video_count',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel_1',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel_2',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel_3',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel_4',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='channel_5',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='send_time',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='content',
            field=models.TextField(default='새로운 영상이 업로드되었습니다.', verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_successful',
            field=models.BooleanField(default=True, verbose_name='발송 성공 여부'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(default='YouTube 알림', max_length=200, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='channel_name',
            field=models.CharField(blank=True, default='기본 채널', max_length=100, null=True, verbose_name='채널 이름'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_video_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 영상 확인 시간'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='구독자', max_length=100, verbose_name='구독자 이름'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notification_time',
            field=models.TimeField(default='09:00', verbose_name='알림 시간'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='youtube_channel_url',
            field=models.URLField(default='https://www.youtube.com/@default', validators=[django.core.validators.URLValidator()], verbose_name='YouTube 채널 URL'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발송 시간'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='subscriptions.subscription', verbose_name='구독'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 상태'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
