# Generated by Django 4.2.7 on 2025-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_emaillog_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='password',
            field=models.CharField(default='defaultpassword123', help_text='구독 정보 수정 시 사용할 비밀번호', max_length=128, verbose_name='비밀번호'),
        ),
    ]
