# Generated by Django 4.2.7 on 2025-06-02 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='이메일'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('email', 'youtube_channel_url')},
        ),
    ]
